blueprint:
  name: Aeotec Siren 6 Alarm
  description: Trigger an alarm on an Aeotec Siren 6 (ZW164) based on sensor activity from Z-Wave JS.
  domain: automation
  input:
    aeotec_siren:
      name: Aeotec Siren 6 Device
      description: Select your Aeotec Siren 6 device.
      selector:
        device:
          integration: zwave_js
          manufacturer: Aeotec
          model: ZW164
    
    # Time condition settings
    enable_time_condition:
      name: Enable Time Condition
      description: Check to enable time-based conditions. The siren will only activate during the specified time range.
      selector:
        boolean: {}
      default: false
    
    start_time:
      name: Siren Active Start Time
      description: The time of day to start allowing the siren to activate.
      selector:
        time: {}
      default: '22:00:00'
    
    end_time:
      name: Siren Active End Time
      description: The time of day to stop allowing the siren to activate.
      selector:
        time: {}
      default: '07:00:00'

    # Trigger settings
    use_door_sensor:
      name: Use Door Sensor
      description: Enable this to use a door sensor as a trigger.
      selector:
        boolean: {}
      default: false
    door_sensor:
      name: Door Sensor
      description: The door sensor to monitor.
      selector:
        entity:
          domain: binary_sensor
          device_class: door
      skip_condition: '{{ not use_door_sensor }}'
    
    use_window_sensor:
      name: Use Window Sensor
      description: Enable this to use a window sensor as a trigger.
      selector:
        boolean: {}
      default: false
    window_sensor:
      name: Window Sensor
      description: The window sensor to monitor.
      selector:
        entity:
          domain: binary_sensor
          device_class: window
      skip_condition: '{{ not use_window_sensor }}'
    
    use_temperature_sensor:
      name: Use Temperature Sensor
      description: Enable this to use a temperature sensor as a trigger.
      selector:
        boolean: {}
      default: false
    temperature_sensor:
      name: Temperature Sensor
      description: The temperature sensor to monitor.
      selector:
        entity:
          domain: sensor
          device_class: temperature
      skip_condition: '{{ not use_temperature_sensor }}'
    temp_units:
      name: Temperature Units
      description: Select Celsius or Fahrenheit.
      selector:
        select:
          options:
            - label: Celsius
              value: 'celsius'
            - label: Fahrenheit
              value: 'fahrenheit'
      skip_condition: '{{ not use_temperature_sensor }}'
      default: 'celsius'
    temp_threshold:
      name: Temperature Threshold
      description: Trigger if the temperature goes above this value.
      selector:
        number:
          min: -40
          max: 100
          step: 1
      skip_condition: '{{ not use_temperature_sensor }}'
      default: 30
    
    use_humidity_sensor:
      name: Use Humidity Sensor
      description: Enable this to use a humidity sensor as a trigger.
      selector:
        boolean: {}
      default: false
    humidity_sensor:
      name: Humidity Sensor
      description: The humidity sensor to monitor.
      selector:
        entity:
          domain: sensor
          device_class: humidity
      skip_condition: '{{ not use_humidity_sensor }}'
    humidity_threshold:
      name: Humidity Threshold
      description: Trigger if the humidity goes above this percentage.
      selector:
        number:
          min: 0
          max: 100
          step: 1
      skip_condition: '{{ not use_humidity_sensor }}'
      default: 80
    
    # Siren and light settings
    siren_tone:
      name: Siren Tone
      description: Select the alarm tone to play. (Number and Name)
      selector:
        select:
          options:
            - label: "1: Ding Dong"
              value: 1
            - label: "2: Ding Dong Tubular Bell"
              value: 2
            - label: "3: Traditional Apartment Buzzer"
              value: 3
            - label: "4: Electric Apartment Buzzer"
              value: 4
            - label: "5: Westminster Chimes"
              value: 5
            - label: "6: Chimes"
              value: 6
            - label: "7: Cuckoo"
              value: 7
            - label: "8: Traditional Bell"
              value: 8
            - label: "9: Smoke Alarm (Low)"
              value: 9
            - label: "10: Smoke Alarm (High)"
              value: 10
            - label: "11: Fire Evacuation Buzzer"
              value: 11
            - label: "12: CO Alarm"
              value: 12
            - label: "13: Klaxon"
              value: 13
            - label: "14: Deep Klaxon"
              value: 14
            - label: "15: Warning Tone"
              value: 15
            - label: "16: Tornado Siren"
              value: 16
            - label: "17: Alarm"
              value: 17
            - label: "18: Deep Alarm Tone"
              value: 18
            - label: "19: Alarm (Archangel tone)"
              value: 19
            - label: "20: Alarm Shrill"
              value: 20
            - label: "21: Digital Siren"
              value: 21
            - label: "22: Alert Series"
              value: 22
            - label: "23: Ship Bell"
              value: 23
            - label: "24: Clock Buzzer"
              value: 24
            - label: "25: Christmas Tree"
              value: 25
            - label: "26: Gong"
              value: 26
            - label: "27: Single Bell Ting"
              value: 27
            - label: "28: Tonal Pulse"
              value: 28
            - label: "29: Upward Tone"
              value: 29
            - label: "30: Door Open"
              value: 30
      default: 17
    
    siren_volume:
      name: Siren Volume
      description: The volume level for the siren (1-100%).
      selector:
        number:
          min: 1
          max: 100
          step: 1
          mode: slider
      default: 100
    
    siren_duration:
      name: Siren Duration
      description: The duration in seconds for the siren to sound.
      selector:
        number:
          min: 1
          max: 3600
          step: 1
          mode: slider
          unit_of_measurement: s
      default: 30
    
    light_effect:
      name: Light Effect
      description: Select a light effect to play with the siren.
      selector:
        select:
          options:
            - label: Off
              value: 'off'
            - label: On (Solid)
              value: 'on'
            - label: Slow Pulse
              value: 'slow_pulse'
            - label: Pulse
              value: 'pulse'
            - label: Fast Pulse
              value: 'fast_pulse'
            - label: Flash
              value: 'flash'
            - label: Strobe
              value: 'strobe'
      default: 'strobe'

  trigger:
    - platform: state
      entity_id: !input door_sensor
      from: 'off'
      to: 'on'
      id: door_sensor
      enabled: !input use_door_sensor
    - platform: state
      entity_id: !input window_sensor
      from: 'off'
      to: 'on'
      id: window_sensor
      enabled: !input use_window_sensor
    - platform: numeric_state
      entity_id: !input temperature_sensor
      above: !input temp_threshold
      id: temp_sensor
      enabled: !input use_temperature_sensor
    - platform: numeric_state
      entity_id: !input humidity_sensor
      above: !input humidity_threshold
      id: humidity_sensor
      enabled: !input use_humidity_sensor

  condition:
    - condition: or
      conditions:
        - condition: and
          conditions:
            - condition: template
              value: '{{ not enable_time_condition }}'
            - condition: not
              conditions:
                - condition: state
                  entity_id: !input aeotec_siren
                  attribute: alarmLevel
                  state: 'on'
        - condition: and
          conditions:
            - condition: template
              value: '{{ enable_time_condition }}'
            - condition: time
              after: !input start_time
              before: !input end_time
            - condition: not
              conditions:
                - condition: state
                  entity_id: !input aeotec_siren
                  attribute: alarmLevel
                  state: 'on'

  action:
    - service: zwave_js.set_value
      data:
        command_class: 112
        property: 37
        value: !input light_effect
      target:
        device_id: !input aeotec_siren
    - service: zwave_js.set_value
      data:
        command_class: 112
        property: 38
        value: !input siren_tone
      target:
        device_id: !input aeotec_siren
    - service: zwave_js.set_value
      data:
        command_class: 112
        property: 39
        value: !input siren_volume
      target:
        device_id: !input aeotec_siren
    - service: zwave_js.play_tone
      data:
        duration: !input siren_duration
      target:
        device_id: !input aeotec_siren
