blueprint:
  name: Aeotec Indoor Siren 6 (ZW164) Security & Environmental Monitor
  description: |
    Comprehensive automation for Aeotec Indoor Siren 6 with multiple trigger options.
    Supports door/window sensors, temperature/humidity monitoring, customizable tones,
    light effects, and time-based conditions.
  domain: automation
  input:
    # Device Selection
    siren_device:
      name: Aeotec Indoor Siren 6
      description: Select your Aeotec Indoor Siren 6 device
      selector:
        device:
          integration: zwave_js
          manufacturer: Aeotec Ltd.
          model: ZW164
    
    # Time Conditions
    enable_time_conditions:
      name: Enable Time Conditions
      description: Check to enable time-based restrictions
      default: false
      selector:
        boolean:
    
    time_start:
      name: Start Time
      description: Siren will only activate after this time
      default: "22:00:00"
      selector:
        time:
    
    time_end:
      name: End Time
      description: Siren will only activate before this time
      default: "06:00:00"
      selector:
        time:
    
    # Door Sensor Configuration
    enable_door_sensor:
      name: Enable Door Sensor
      description: Enable door sensor monitoring
      default: false
      selector:
        boolean:
    
    door_sensor:
      name: Door Sensor
      description: Select door sensor entity
      default: []
      selector:
        entity:
          domain: binary_sensor
          device_class: door
    
    # Window Sensor Configuration
    enable_window_sensor:
      name: Enable Window Sensor
      description: Enable window sensor monitoring
      default: false
      selector:
        boolean:
    
    window_sensor:
      name: Window Sensor
      description: Select window sensor entity
      default: []
      selector:
        entity:
          domain: binary_sensor
          device_class: window
    
    # Temperature Sensor Configuration
    enable_temperature_sensor:
      name: Enable Temperature Monitoring
      description: Enable temperature threshold monitoring
      default: false
      selector:
        boolean:
    
    temperature_sensor:
      name: Temperature Sensor
      description: Select temperature sensor entity
      default: []
      selector:
        entity:
          domain: sensor
          device_class: temperature
    
    temperature_unit:
      name: Temperature Unit
      description: Select temperature unit
      default: "celsius"
      selector:
        select:
          options:
            - label: "Celsius (°C)"
              value: "celsius"
            - label: "Fahrenheit (°F)"
              value: "fahrenheit"
    
    temperature_threshold:
      name: Temperature Threshold
      description: Temperature threshold to trigger siren
      default: 30
      selector:
        number:
          min: -40
          max: 100
          step: 0.5
          unit_of_measurement: "°"
    
    temperature_condition:
      name: Temperature Condition
      description: Trigger when temperature is above or below threshold
      default: "above"
      selector:
        select:
          options:
            - label: "Above threshold"
              value: "above"
            - label: "Below threshold"
              value: "below"
    
    # Humidity Sensor Configuration
    enable_humidity_sensor:
      name: Enable Humidity Monitoring
      description: Enable humidity threshold monitoring
      default: false
      selector:
        boolean:
    
    humidity_sensor:
      name: Humidity Sensor
      description: Select humidity sensor entity
      default: []
      selector:
        entity:
          domain: sensor
          device_class: humidity
    
    humidity_threshold:
      name: Humidity Threshold
      description: Humidity threshold to trigger siren (%)
      default: 70
      selector:
        number:
          min: 0
          max: 100
          step: 1
          unit_of_measurement: "%"
    
    humidity_condition:
      name: Humidity Condition
      description: Trigger when humidity is above or below threshold
      default: "above"
      selector:
        select:
          options:
            - label: "Above threshold"
              value: "above"
            - label: "Below threshold"
              value: "below"
    
    # Siren Configuration
    siren_tone:
      name: Siren Tone
      description: Select the siren tone
      default: 1
      selector:
        select:
          options:
            - label: "1 - Ding Dong"
              value: 1
            - label: "2 - Ding Dong Ding"
              value: 2
            - label: "3 - Traditional Door Chime"
              value: 3
            - label: "4 - Police Siren"
              value: 4
            - label: "5 - Evacuation"
              value: 5
            - label: "6 - Beep Beep"
              value: 6
            - label: "7 - Beep"
              value: 7
            - label: "8 - Ding"
              value: 8
            - label: "9 - Dong"
              value: 9
            - label: "10 - Hee Haw"
              value: 10
            - label: "11 - Hallelujah"
              value: 11
            - label: "12 - Hush Little Baby"
              value: 12
            - label: "13 - Jingle Bells"
              value: 13
            - label: "14 - Mary Had a Little Lamb"
              value: 14
            - label: "15 - Westminster Chimes"
              value: 15
            - label: "16 - Traditional Cuckoo"
              value: 16
            - label: "17 - Intermittent Alarm"
              value: 17
            - label: "18 - Continuous Alarm"
              value: 18
            - label: "19 - Emergency Sound"
              value: 19
            - label: "20 - Clock Alarm"
              value: 20
            - label: "21 - Fire Alarm"
              value: 21
            - label: "22 - Ambulance"
              value: 22
            - label: "23 - Police Car"
              value: 23
            - label: "24 - Door Chime Extended"
              value: 24
            - label: "25 - Arm/Disarm Beep"
              value: 25
            - label: "26 - Telephone Ring"
              value: 26
            - label: "27 - Smoke Alarm"
              value: 27
            - label: "28 - Co Alarm"
              value: 28
            - label: "29 - Test Alarm"
              value: 29
            - label: "30 - Wakeup"
              value: 30
    
    siren_volume:
      name: Siren Volume
      description: Volume level (0-100%)
      default: 80
      selector:
        number:
          min: 0
          max: 100
          step: 5
          unit_of_measurement: "%"
    
    siren_duration:
      name: Siren Duration
      description: Duration in seconds (1-600 seconds)
      default: 10
      selector:
        number:
          min: 1
          max: 600
          step: 1
          unit_of_measurement: "sec"
    
    # Light Effect Configuration
    light_effect:
      name: Light Effect
      description: Select the light effect
      default: 0
      selector:
        select:
          options:
            - label: "0 - Off"
              value: 0
            - label: "1 - Solid Color"
              value: 1
            - label: "2 - Slow Blink"
              value: 2
            - label: "3 - Fast Blink"
              value: 3
            - label: "4 - Pulse"
              value: 4
            - label: "5 - Strobe"
              value: 5
    
    light_color:
      name: Light Color
      description: Select the light color
      default: 1
      selector:
        select:
          options:
            - label: "1 - Red"
              value: 1
            - label: "2 - Orange"
              value: 2
            - label: "3 - Yellow"
              value: 3
            - label: "4 - Green"
              value: 4
            - label: "5 - Blue"
              value: 5
            - label: "6 - Indigo"
              value: 6
            - label: "7 - Violet"
              value: 7

# Variables for conditional logic
variables:
  door_enabled: !input enable_door_sensor
  window_enabled: !input enable_window_sensor
  temp_enabled: !input enable_temperature_sensor
  humidity_enabled: !input enable_humidity_sensor
  time_enabled: !input enable_time_conditions
  temp_unit: !input temperature_unit
  temp_condition: !input temperature_condition
  humidity_condition: !input humidity_condition
  siren_tone: !input siren_tone
  light_effect: !input light_effect
  light_color: !input light_color

# Triggers
trigger:
  # Door sensor trigger
  - platform: state
    entity_id: !input door_sensor
    to: 'on'
    id: door_opened
    enabled: "{{ door_enabled }}"
  
  # Window sensor trigger
  - platform: state
    entity_id: !input window_sensor
    to: 'on'
    id: window_opened
    enabled: "{{ window_enabled }}"
  
  # Temperature sensor trigger
  - platform: numeric_state
    entity_id: !input temperature_sensor
    above: !input temperature_threshold
    id: temp_above
    enabled: "{{ temp_enabled and temp_condition == 'above' }}"
  
  - platform: numeric_state
    entity_id: !input temperature_sensor
    below: !input temperature_threshold
    id: temp_below
    enabled: "{{ temp_enabled and temp_condition == 'below' }}"
  
  # Humidity sensor trigger
  - platform: numeric_state
    entity_id: !input humidity_sensor
    above: !input humidity_threshold
    id: humidity_above
    enabled: "{{ humidity_enabled and humidity_condition == 'above' }}"
  
  - platform: numeric_state
    entity_id: !input humidity_sensor
    below: !input humidity_threshold
    id: humidity_below
    enabled: "{{ humidity_enabled and humidity_condition == 'below' }}"

# Conditions
condition:
  - condition: or
    conditions:
      # If time conditions are disabled, always allow
      - condition: template
        value_template: "{{ not time_enabled }}"
      
      # If time conditions are enabled, check time range
      - condition: and
        conditions:
          - condition: template
            value_template: "{{ time_enabled }}"
          - condition: time
            after: !input time_start
            before: !input time_end

# Actions
action:
  - service: zwave_js.set_config_parameter
    target:
      device_id: !input siren_device
    data:
      parameter: 37
      value: !input siren_tone
  
  - service: zwave_js.set_config_parameter
    target:
      device_id: !input siren_device
    data:
      parameter: 38
      value: !input siren_volume
  
  - service: zwave_js.set_config_parameter
    target:
      device_id: !input siren_device
    data:
      parameter: 39
      value: !input siren_duration
  
  - service: zwave_js.set_config_parameter
    target:
      device_id: !input siren_device
    data:
      parameter: 40
      value: !input light_effect
  
  - service: zwave_js.set_config_parameter
    target:
      device_id: !input siren_device
    data:
      parameter: 41
      value: !input light_color
  
  - service: switch.turn_on
    target:
      device_id: !input siren_device
  
  - service: logbook.log
    data:
      name: "Aeotec Siren Activated"
      message: >
        {% if trigger.id == 'door_opened' %}
          Door sensor triggered siren activation
        {% elif trigger.id == 'window_opened' %}
          Window sensor triggered siren activation
        {% elif trigger.id in ['temp_above', 'temp_below'] %}
          Temperature {{ trigger.to_state.state }}{{ '°C' if temp_unit == 'celsius' else '°F' }} triggered siren activation
        {% elif trigger.id in ['humidity_above', 'humidity_below'] %}
          Humidity {{ trigger.to_state.state }}% triggered siren activation
        {% endif %}

mode: single
max_exceeded: silent
