blueprint:
  name: Aeotec Siren 6 - Advanced Control (Sensors)
  description: Trigger an Aeotec Siren 6 (ZW164) with customizable tones, volume, and duration based on selected door, temperature, or humidity sensors. This version allows selecting between Celsius and Fahrenheit for temperature thresholds.
  domain: automation
  author: Home Assistant Community
  input:
    siren_device:
      name: Siren Device
      description: The Z-Wave JS device for the Aeotec Siren 6.
      selector:
        device:
          integration: zwave_js
    siren_tone:
      name: Siren Tone
      description: Select one of the 30 available tones by name.
      default: '1'
      selector:
        select:
          options:
            - label: "1. Ding Dong"
              value: '1'
            - label: "2. Ding Dong Tubular"
              value: '2'
            - label: "3. Traditional Apartment Buzzer"
              value: '3'
            - label: "4. Electric Apartment Buzzer"
              value: '4'
            - label: "5. Westminster Chimes"
              value: '5'
            - label: "6. Chimes"
              value: '6'
            - label: "7. Cuckoo"
              value: '7'
            - label: "8. Traditional Bell"
              value: '8'
            - label: "9. Smoke Alarm"
              value: '9'
            - label: "10. Smoke Alarm 2"
              value: '10'
            - label: "11. Fire Evacuation Buzzer"
              value: '11'
            - label: "12. CO Alarm"
              value: '12'
            - label: "13. Klaxon"
              value: '13'
            - label: "14. Deep Klaxon"
              value: '14'
            - label: "15. Warning Tone"
              value: '15'
            - label: "16. Tornado Siren"
              value: '16'
            - label: "17. Alarm"
              value: '17'
            - label: "18. Deep Alarm"
              value: '18'
            - label: "19. Alarm Archangel"
              value: '19'
            - label: "20. Alarm Shrill"
              value: '20'
            - label: "21. Digital Siren"
              value: '21'
            - label: "22. Alert Series"
              value: '22'
            - label: "23. Ship Bell"
              value: '23'
            - label: "24. Clock Buzzer"
              value: '24'
            - label: "25. Christmas Tree"
              value: '25'
            - label: "26. Gong"
              value: '26'
            - label: "27. Single Bell Ting"
              value: '27'
            - label: "28. Tonal Pulse"
              value: '28'
            - label: "29. Upward Tone"
              value: '29'
            - label: "30. Door Open"
              value: '30'
    siren_volume:
      name: Siren Volume
      description: Set the volume level of the siren (0-100%).
      default: 80
      selector:
        number:
          min: 0
          max: 100
          step: 1
          mode: slider
    siren_duration:
      name: Siren Duration
      description: The duration in seconds that the tone should play.
      default: 5
      selector:
        number:
          min: 0
          max: 600
          step: 1
          mode: box
    enable_door_sensors:
      name: Enable Door/Window Sensors?
      description: Check this box to enable the door/window sensor trigger.
      default: false
      selector:
        boolean: {}
    door_sensors:
      name: Door/Window Sensors (Optional)
      description: Select door or window contact sensors that will trigger the alarm when opened. Only active if enabled above.
      default: []
      selector:
        entity:
          domain: binary_sensor
          multiple: true
          device_class: 
            - door
            - window
    enable_temp_sensors:
      name: Enable Temperature Sensors?
      description: Check this box to enable the temperature sensor trigger.
      default: false
      selector:
        boolean: {}
    temp_sensors:
      name: Temperature Sensors (Optional)
      description: Select temperature sensors to trigger the alarm. Only active if enabled above.
      default: []
      selector:
        entity:
          domain: sensor
          device_class: temperature
          multiple: true
    temp_unit:
      name: Temperature Unit
      description: Select the unit of measurement for the temperature threshold.
      default: 'Fahrenheit'
      selector:
        select:
          options:
            - label: "Fahrenheit (°F)"
              value: 'Fahrenheit'
            - label: "Celsius (°C)"
              value: 'Celsius'
    temp_threshold:
      name: Temperature Threshold
      description: Trigger the alarm when temperature goes above this value.
      default: 85
      selector:
        number:
          min: -50
          max: 200
          step: 1
    enable_humidity_sensors:
      name: Enable Humidity Sensors?
      description: Check this box to enable the humidity sensor trigger.
      default: false
      selector:
        boolean: {}
    humidity_sensors:
      name: Humidity Sensors (Optional)
      description: Select humidity sensors to trigger the alarm. Only active if enabled above.
      default: []
      selector:
        entity:
          domain: sensor
          device_class: humidity
          multiple: true
    humidity_threshold:
      name: Humidity Threshold
      description: Trigger the alarm when humidity goes above this value.
      default: 70
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
          step: 1

variables:
  temp_unit: !input temp_unit
  temp_threshold: !input temp_threshold

trigger:
  - platform: state
    entity_id: !input door_sensors
    to: 'on'
  - platform: numeric_state
    entity_id: !input humidity_sensors
    above: !input humidity_threshold
  - platform: template
    value_template: >
      {% if enable_temp_sensors and temp_sensors is defined and temp_sensors %}
        {% for sensor in temp_sensors %}
          {% set temp_value = states(sensor) | float %}
          {% if temp_unit == 'Fahrenheit' %}
            {% set converted_temp = (temp_value * 9/5) + 32 %}
          {% else %}
            {% set converted_temp = temp_value %}
          {% endif %}
          {% if converted_temp > temp_threshold | float %}
            true
          {% endif %}
        {% endfor %}
      {% endif %}

action:
  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: and
                conditions:
                  - condition: template
                    value_template: "{{ enable_door_sensors }}"
                  - condition: state
                    entity_id: !input door_sensors
                    to: 'on'
              - condition: and
                conditions:
                  - condition: template
                    value_template: "{{ enable_temp_sensors }}"
                  - condition: template
                    value_template: "{{ is_state('trigger.platform', 'template') }}"
              - condition: and
                conditions:
                  - condition: template
                    value_template: "{{ enable_humidity_sensors }}"
                  - condition: numeric_state
                    entity_id: !input humidity_sensors
                    above: !input humidity_threshold
        sequence:
          - service: siren.turn_on
            target:
              device_id: !input siren_device
            data:
              tone: !input siren_tone | int
              volume_level: "{{ (states('input_number.siren_volume') | float) / 100 }}"
              duration: "{{ states('input_number.siren_duration') | int }}"
mode: single
