blueprint:
  name: Advanced Motion Activated Lighting
  description: >
    Turn lights on when motion is detected or doors open, with multiple optional conditions
    and occupancy detection to keep lights on while room is occupied.
  domain: automation
  input:
    # Primary Triggers
    motion_sensors:
      name: Motion Sensors or Door Sensors
      description: Select one or more motion sensors or door sensors that will trigger the automation
      selector:
        entity:
          multiple: true
          filter:
            - domain: binary_sensor
    
    # Light Control
    light_control_type:
      name: Light Control Type
      description: Choose whether to control individual lights/devices or use scenes
      selector:
        select:
          options:
            - label: "Individual Lights/Devices"
              value: "devices"
            - label: "Scenes"
              value: "scenes"
      default: "devices"
    
    lights:
      name: Lights to Turn On
      description: Select lights or devices to turn on (only used if Individual Lights/devices is selected above)
      default: []
      selector:
        entity:
          multiple: true
          filter:
            - domain: light
            - domain: switch
            - domain: fan
    
    on_scene:
      name: Scene to Activate
      description: Scene to activate when motion is detected (only used if Scenes is selected above)
      default: ""
      selector:
        entity:
          filter:
            - domain: scene
    
    off_scene:
      name: Scene to Deactivate
      description: Scene to activate when turning off (only used if Scenes is selected above)
      default: ""
      selector:
        entity:
          filter:
            - domain: scene
    
    # Timer
    timer_duration:
      name: Timer Duration
      description: How long to wait before turning off lights after all sensors are clear
      default:
        minutes: 5
      selector:
        duration:
    
    # Optional: Device Tracking
    device_tracking_options:
      name: Device Tracking Options
      description: Control automation based on device presence
      collapsed: true
      input:
        enable_device_tracking:
          name: Enable Device Tracking
          description: Enable device presence checking
          default: false
          selector:
            boolean:
        
        tracked_device:
          name: Device to Track
          description: Device that must be present/absent for automation to run
          default: ""
          selector:
            entity:
              filter:
                - domain: device_tracker
                - domain: person
        
        device_zone:
          name: Zone for Device Check
          description: Zone where device should be present for automation to run
          default: "home"
          selector:
            text:
        
        device_presence_required:
          name: Device Must Be Present
          description: If enabled, device must be in zone. If disabled, device must NOT be in zone
          default: true
          selector:
            boolean:
    
    # Optional: Time Restrictions
    time_restriction_options:
      name: Time Restriction Options
      description: Control when automation runs based on time of day
      collapsed: true
      input:
        enable_time_restriction:
          name: Enable Time Restrictions
          description: Only run automation between certain times
          default: false
          selector:
            boolean:
        
        start_time:
          name: Start Time
          description: Earliest time to run automation
          default: "00:00:00"
          selector:
            time:
        
        end_time:
          name: End Time
          description: Latest time to run automation
          default: "23:59:59"
          selector:
            time:
    
    # Optional: Day Restrictions
    day_restriction_options:
      name: Day of Week Restriction Options
      description: Control which days automation runs
      collapsed: true
      input:
        enable_day_restriction:
          name: Enable Day of Week Restrictions
          description: Only run automation on selected days
          default: false
          selector:
            boolean:
        
        allowed_days:
          name: Allowed Days
          description: Days when automation is allowed to run
          default:
            - mon
            - tue
            - wed
            - thu
            - fri
            - sat
            - sun
          selector:
            select:
              multiple: true
              options:
                - label: "Monday"
                  value: "mon"
                - label: "Tuesday"
                  value: "tue"
                - label: "Wednesday"
                  value: "wed"
                - label: "Thursday"
                  value: "thu"
                - label: "Friday"
                  value: "fri"
                - label: "Saturday"
                  value: "sat"
                - label: "Sunday"
                  value: "sun"
    
    # Optional: Light Sensor
    light_sensor_options:
      name: Light Sensor Options
      description: Control automation based on ambient light level
      collapsed: true
      input:
        enable_light_sensor:
          name: Enable Light Sensor
          description: Only run when light level is below threshold
          default: false
          selector:
            boolean:
        
        light_sensor:
          name: Light Sensor
          description: Sensor to check light level
          default: ""
          selector:
            entity:
              filter:
                - device_class: illuminance
        
        light_threshold:
          name: Light Threshold
          description: Light level below which automation runs
          default: 100
          selector:
            number:
              min: 0
              max: 1000
              step: 10
              unit_of_measurement: lux
    
    # Optional: Occupancy Sensor
    occupancy_sensor_options:
      name: Occupancy Detection Options
      description: Use additional sensors to detect room occupancy
      collapsed: true
      input:
        enable_occupancy_sensor:
          name: Enable Occupancy Detection
          description: Use additional sensor to detect room occupancy
          default: false
          selector:
            boolean:
        
        occupancy_sensors:
          name: Occupancy Sensors
          description: Additional sensors to detect room occupancy (lights stay on while these are active)
          default: []
          selector:
            entity:
              multiple: true
              filter:
                - domain: binary_sensor
    
    # Optional: Wait for All Sensors
    wait_for_all_sensors:
      name: Wait for All Sensors Clear
      description: Wait until ALL motion/door sensors are clear before starting timer
      default: true
      selector:
        boolean:
    
    # Optional: Extra Devices to Turn Off
    extra_turnoff_options:
      name: Extra Turn Off Options
      description: Turn off additional devices when automation ends
      collapsed: true
      input:
        enable_extra_turnoff:
          name: Enable Extra Turn Off
          description: Turn off additional devices/scenes when timer expires
          default: false
          selector:
            boolean:
        
        extra_devices:
          name: Extra Devices to Turn Off
          description: Additional devices to turn off when automation ends
          default: []
          selector:
            entity:
              multiple: true
              filter:
                - domain: light
                - domain: switch
                - domain: fan
        
        extra_off_scenes:
          name: Extra Scenes to Activate
          description: Additional scenes to activate when automation ends
          default: []
          selector:
            entity:
              multiple: true
              filter:
                - domain: scene

variables:
  motion_sensors: !input motion_sensors
  lights: !input lights
  on_scene: !input on_scene
  off_scene: !input off_scene
  light_control_type: !input light_control_type
  timer_duration: !input timer_duration
  enable_device_tracking: !input device_tracking_options.enable_device_tracking
  tracked_device: !input device_tracking_options.tracked_device
  device_zone: !input device_tracking_options.device_zone
  device_presence_required: !input device_tracking_options.device_presence_required
  enable_time_restriction: !input time_restriction_options.enable_time_restriction
  start_time: !input time_restriction_options.start_time
  end_time: !input time_restriction_options.end_time
  enable_day_restriction: !input day_restriction_options.enable_day_restriction
  allowed_days: !input day_restriction_options.allowed_days
  enable_light_sensor: !input light_sensor_options.enable_light_sensor
  light_sensor: !input light_sensor_options.light_sensor
  light_threshold: !input light_sensor_options.light_threshold
  enable_occupancy_sensor: !input occupancy_sensor_options.enable_occupancy_sensor
  occupancy_sensors: !input occupancy_sensor_options.occupancy_sensors
  wait_for_all_sensors: !input wait_for_all_sensors
  enable_extra_turnoff: !input extra_turnoff_options.enable_extra_turnoff
  extra_devices: !input extra_turnoff_options.extra_devices
  extra_off_scenes: !input extra_turnoff_options.extra_off_scenes

trigger:
  - platform: state
    entity_id: !input motion_sensors
    to: 
      - "on"
      - "open"
      - "detected"
    id: "motion_detected"
  - platform: state
    entity_id: !input motion_sensors
    to:
      - "off"
      - "closed"
      - "clear"
    id: "motion_cleared"

condition: []

action:
  - choose:
      # Motion/Door Detected - Turn On Lights
      - conditions:
          - condition: trigger
            id: "motion_detected"
          # Check device tracking condition
          - condition: or
            conditions:
              - condition: template
                value_template: "{{ not enable_device_tracking }}"
              - condition: and
                conditions:
                  - condition: template
                    value_template: "{{ enable_device_tracking }}"
                  - condition: template
                    value_template: >
                      {% if device_presence_required %}
                        {{ is_state(tracked_device, device_zone) }}
                      {% else %}
                        {{ not is_state(tracked_device, device_zone) }}
                      {% endif %}
          # Check time restriction
          - condition: or
            conditions:
              - condition: template
                value_template: "{{ not enable_time_restriction }}"
              - condition: time
                after: !input start_time
                before: !input end_time
          # Check day restriction
          - condition: or
            conditions:
              - condition: template
                value_template: "{{ not enable_day_restriction }}"
              - condition: template
                value_template: "{{ now().strftime('%a')|lower in allowed_days }}"
          # Check light sensor
          - condition: or
            conditions:
              - condition: template
                value_template: "{{ not enable_light_sensor }}"
              - condition: and
                conditions:
                  - condition: template
                    value_template: "{{ enable_light_sensor and light_sensor != '' }}"
                  - condition: numeric_state
                    entity_id: !input light_sensor
                    below: !input light_threshold
        sequence:
          - choose:
              # Turn on individual devices
              - conditions:
                  - condition: template
                    value_template: "{{ light_control_type == 'devices' }}"
                sequence:
                  - service: homeassistant.turn_on
                    target:
                      entity_id: !input lights
              # Activate scene
              - conditions:
                  - condition: template
                    value_template: "{{ light_control_type == 'scenes' and on_scene != '' }}"
                sequence:
                  - service: scene.turn_on
                    target:
                      entity_id: !input on_scene
      
      # Motion/Door Cleared - Start Timer
      - conditions:
          - condition: trigger
            id: "motion_cleared"
        sequence:
          # Wait for all motion sensors to be clear if enabled
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ wait_for_all_sensors }}"
                sequence:
                  - wait_template: >
                      {% set sensors = motion_sensors if motion_sensors is iterable and motion_sensors is not string else [motion_sensors] %}
                      {{ sensors | select('is_state', ['on', 'open', 'detected']) | list | length == 0 }}
          
          # Wait for occupancy sensors to be clear if enabled
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ enable_occupancy_sensor }}"
                sequence:
                  - wait_template: >
                      {% set occ_sensors = occupancy_sensors if occupancy_sensors is iterable and occupancy_sensors is not string else [occupancy_sensors] %}
                      {{ occ_sensors | select('is_state', ['on', 'open', 'detected']) | list | length == 0 }}
          
          # Wait for timer duration
          - delay: !input timer_duration
          
          # Turn off lights or activate off scene
          - choose:
              # Turn off individual devices
              - conditions:
                  - condition: template
                    value_template: "{{ light_control_type == 'devices' }}"
                sequence:
                  - service: homeassistant.turn_off
                    target:
                      entity_id: !input lights
              # Activate off scene
              - conditions:
                  - condition: template
                    value_template: "{{ light_control_type == 'scenes' and off_scene != '' }}"
                sequence:
                  - service: scene.turn_on
                    target:
                      entity_id: !input off_scene
          
          # Turn off extra devices if enabled
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ enable_extra_turnoff }}"
                sequence:
                  - service: homeassistant.turn_off
                    target:
                      entity_id: !input extra_devices
                  - service: scene.turn_on
                    target:
                      entity_id: !input extra_off_scenes

mode: restart
