blueprint:
  name: Unifi Protect Camera Cast to Google Display with Optional Cool-Down
  description: >
     # Cast Unifi Protect camera to Google Display based on triggers with an optional cool-down delay.

     Cast Unifi Protect camera to Google Display based on triggers with an optional cool-down delay.

     <details>
     <summary><b>Instructions:</b></summary>

    
      - **Trigger:**
        - The trigger can be the doorbell buton or any other binary sensor from the Unifi Camera.

      - **Camera:**
          - Select a single Unifi Camera (Recommend to use the Low Resolution Stream (insecure) and also set the stream to preload.
      
      - **Cast Device:**
          - Select a single Cast device or Group.
      
      - **Volume Level:**
          - Adjust your desired volume level.

      - **Time Limit:**
        - This is the amount of time the stream will be displayed on the Cast Devices.

      - **Trigger Binary Sensors:**
        - Select One or more Binary Sensors from the Unifi Camera.

      - **Cool-Down Delay:**
        - This is the amount of time that needs to pass before the automation will trigger again.

      
      </details>           
  
  domain: automation
  input:
    camera:
      name: Camera
      description: Select the Unifi Protect camera to cast.
      selector:
        entity:
          domain: camera
          integration: unifiprotect
    cast_device:
      name: Cast Device
      description: Select a Google Cast device or a media player group.
      selector:
        entity:
          domain: media_player
          multiple: false
    volume_level:
      name: Volume Level
      description: Set the volume for the cast device.
      default: 50
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: '%'
    time_limit:
      name: Time Limit
      description: Set the time limit for casting the camera stream.
      default: 30
      selector:
        number:
          min: 10
          max: 300
          unit_of_measurement: seconds
    trigger_binary_sensors:
      name: Trigger Binary Sensors
      description: Select multiple binary sensors that trigger the automation.
      selector:
        entity:
          domain: binary_sensor
          integration: unifiprotect
          multiple: true
    cool_down_delay:
      name: Cool-Down Delay (optional)
      description: Set the cool-down delay after triggering.
      default: None
      selector:
        number:
          min: 300
          max: 3600
          unit_of_measurement: seconds
trigger:
  - platform: state
    entity_id: !input trigger_binary_sensors
    to: 'on'
action:
  - wait_template: >
      {% set last_run = state_attr('automation.{{ automation.entity_id }}', 'last_triggered') %}
      {% if last_run is none %}
        true
      {% else %}
        {{ now() - last_run > timedelta(seconds=input.cool_down_delay) }}
      {% endif %}
  - service: media_player.volume_set
    data:
      volume_level: "{{ (input.volume_level / 100) | float }}"
    target:
      entity_id: !input cast_device
  - service: camera.play_stream
    data:
      format: hls
      media_player: !input cast_device
    target:
      entity_id: !input camera  
  - delay: !input time_limit
  - service: media_player.turn_off
    target:
      entity_id: !input cast_device
mode: single
