blueprint:
  name: Unifi Protect Camera Cast to Google Display
  description: Cast Unifi Protect camera to Google Display for chosen triggers.
  domain: automation
  input:
    camera:
      name: Camera
      description: Select the Unifi Protect camera to cast.
      selector:
        entity:
          domain: camera
          integration: unifiprotect
    cast_device:
      name: Google Cast Device
      description: Select the Google Cast device to cast to.
      selector:
        entity:
          domain: media_player
          integration: cast
    time_limit:
      name: Time Limit
      description: Set the time limit for casting the camera stream.
      default: 30
      selector:
        number:
          min: 10
          max: 300
          unit_of_measurement: seconds

trigger:
  - platform: state
    entity_id: !input camera
    to: "on" # Trigger when the camera state changes to "on"
    variables:
      event_types: "{{ state_attr(trigger.entity_id, 'event_types') }}"
    condition: "{{ event_types is not none and 'ring' in event_types }}"

action:
  - service: camera.play_stream
    data:
      format: hls
      media_player: !input cast_device
    target:
      entity_id: !input camera  
  - delay: !input time_limit
  - service: media_player.turn_off
    target:
      entity_id: !input cast_device
      
mode: single
