blueprint:
  name: Unifi Protect Camera Cast to Google Displays
  description: Cast Unifi Protect camera to Google Display based on any of the selected triggers.
  domain: automation
  input:
    camera:
      name: Camera
      description: Select the Unifi Protect camera to cast.
      selector:
        entity:
          domain: camera
          integration: unifiprotect
    cast_device:
      name: Cast Device
      description: Select a Google Cast device or a media player group.
      selector:
        entity:
          domain: media_player
          multiple: false
    time_limit:
      name: Time Limit
      description: Set the time limit for casting the camera stream.
      default: 30
      selector:
        number:
          min: 10
          max: 300
          unit_of_measurement: seconds
    trigger_binary_sensors:
      name: Trigger Binary Sensors
      description: Select one or more binary sensors that trigger the automation.
      selector:
        entity:
          domain: binary_sensor
          integration: unifiprotect
          multiple: true
trigger:
  - platform: state
    entity_id: !input trigger_binary_sensors
    to: 'on'
action:
  - service: camera.play_stream
    data:
      format: hls
      media_player: !input cast_device
    target:
      entity_id: !input camera  
  - delay: !input time_limit
  - service: media_player.turn_off
    target:
      entity_id: !input cast_device
mode: single
